[package]
name = "Rust-server"
version = "0.1.0"
authors = ["Vladimir Tambovtsev <vladimir.tambovtsev@dataart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
